##in development. may not work
FROM bellsoft/liberica-openjdk-alpine:17
WORKDIR /
ADD downloader-0.0.1-SNAPSHOT.jar downloader-0.0.1-SNAPSHOT.jar
#EXPOSE 8080
CMD java - jar ../../../downloader/build/libs/downloader-0.0.1-SNAPSHOT.jar